version: 2.1

jobs:
  saluda:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Hola mundo"
  despidete:
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys:
          fingerprints:
            - "BUZHqUiqV7cNr8OvpmqbrDap8cT4oe4ZFi3ePqrrZeg"
      - run: mkdir app
      - run: cd app && git clone git@github.com:luiss1981/cc-prueba.git

workflows:
  flow1:
    jobs:
      - saluda
      - despidete
  flow2:
    jobs:
      - saluda
      - despidete:
          requires:
            - saluda
  flow3:
    jobs:
      - saluda
      - approval:
          type: approval
          requires:
            - saluda
      - despidete:
          requires:
            - approval