version: 2.1

jobs:
  saluda:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Hola mundo"
  despidete:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "Adios mundo"

workflows:
  flow1:
    jobs:
      - saluda
      - despidete
  flow2:
    jobs:
      - saluda
      - despidete:
          requires:
            - saluda
  flow3:
    jobs:
      - saluda
      - approve:
          type: approval
          requires:
            - saluda
      - despidete:
          requires:
            - approval